### ISSUE TITLE
"gulp caper" issue

### ISSUE THREAD

**Issue by ArturKarbone** [ArturKarbone/CatalogScraper#4]
can't launch "gulp caper" after "npm install"

Looks like caspesjs is a dependency in package.json. Any ideas?

Keep getting:

/bin/sh: casperjs: command not found

[15:30:36] 'casper' errored after 12 ms
[15:30:36] Error: Command failed: casperjs playground/swipingPages.js
/bin/sh: casperjs: command not found

    at ChildProcess.exithandler (child_process.js:210:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:504:12)

**Comment by DmitryAlCh** [comment]
Capser.js is not a node module, that is why. There are 2 things.
1. download and unzip phantom.js ---> add path to pantomjs.exe inside system environmental variables "PATH"
2. do the same thing for Casper.js.
Node cannot run them by itself.

**Comment by ArturKarbone** [comment]
looks like there is an official way to do that
```
npm install -g casperjs 

```
